package com.nonofy.game.domain.usecase

import com.nonofy.game.domain.models.Solution
import com.nonofy.ui.components.pixelbox.PixelState
import dagger.hilt.android.scopes.ViewModelScoped
import javax.inject.Inject

class GetSolutionByIdUseCase @Inject constructor() {
    fun run() = Solution(
        pixels = listOf(
            listOf(
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty
            ),
            listOf(
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled
            ),
            listOf(
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty
            ),
            listOf(
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled
            ),
            listOf(
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty
            ),
            listOf(
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled
            ),
            listOf(
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty
            ),
            listOf(
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled
            ),
            listOf(
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty
            ),
            listOf(
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled,
                PixelState.Empty,
                PixelState.Filled
            )
        ),
        numFilledPixels = 50
    )
}